<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function welcome_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Adding custom validation for the welcome page type field.
  if ($form_id == 'custom_form_id') {
  $form['gender']['#title'] = "Gener new";
  $form['student_phone']['#title'] = "Student Mobile Number:";
  $form['student_dob']['#title'] = "Birthday Celebration On:";
  $form['high_school']['tests_taken']['#title'] = "Private/Regular:";
  $form['Select_Cast']['#title'] = "Caste Category:";
  $form['text area']['#title'] = "Give A Brief Intro About Yourself:";
   $form['#validate'][] = 'welcome_module_customform_validate';
  }
}
/**
 * Validates submission values in the FORM_ID() form.
 */
function welcome_module_customform_validate(array &$form, FormStateInterface $form_state) {
     if(strlen($form_state->getValue('student_phone')) < 8) {
        $form_state->setErrorByName('student_phone', 'Please enter your 8-digit Contact Number');
      }
}
